export const SET_TASKS = 'SET_TASKS';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SET_TASK_LIST_STATE = 'SET_TASK_LIST_STATE';

export const SET_AUTHORIZATION_STATE = 'SET_AUTHORIZATION_STATE';
export const RESET_AUTHORIZATION_STATE = 'RESET_AUTHORIZATION_STATE';

export const SET_DIALOG_OPEN = 'SET_DIALOG_OPEN';
export const SET_DIALOG_BUSY = 'SET_DIALOG_BUSY';

export const SET_DIALOG_FIELD_VALUE = 'SET_DIALOG_FIELD_VALUE';

export const SET_DIALOG_FIELD_ERROR = 'SET_DIALOG_FIELD_ERROR';
export const RESET_DIALOG_FIELD_ERROR = 'RESET_DIALOG_FIELD_ERROR';

export const SET_DIALOG_GENERAL_ERROR = 'SET_DIALOG_GENERAL_ERROR';
export const RESET_DIALOG_GENERAL_ERROR = 'RESET_DIALOG_GENERAL_ERROR';

export const RESET_DIALOG_STATE = 'RESET_DIALOG_STATE';
