export const SET_TASKS = 'SET_TASKS';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SET_TASK_LIST_STATE = 'SET_TASK_LIST_STATE';

export const SET_TASK_MANAGE_DIALOG_OPEN = 'SET_TASK_MANAGE_DIALOG_OPEN';
export const SET_TASK_MANAGE_DIALOG_BUSY = 'SET_TASK_MANAGE_DIALOG_BUSY';

export const SET_TASK_MANAGE_DIALOG_FIELD_VALUE = 'SET_TASK_MANAGE_DIALOG_FIELD_VALUE';

export const SET_TASK_MANAGE_DIALOG_FIELD_ERROR = 'SET_TASK_MANAGE_DIALOG_FIELD_ERROR';
export const RESET_TASK_MANAGE_DIALOG_FIELD_ERROR = 'RESET_TASK_MANAGE_DIALOG_FIELD_ERROR';

export const SET_TASK_MANAGE_DIALOG_GENERAL_ERROR = 'SET_TASK_MANAGE_DIALOG_GENERAL_ERROR';
export const RESET_TASK_MANAGE_DIALOG_GENERAL_ERROR = 'RESET_TASK_MANAGE_DIALOG_GENERAL_ERROR';

export const RESET_TASK_MANAGE_DIALOG_STATE = 'RESET_TASK_MANAGE_DIALOG_STATE';

export const SET_LOGIN_DIALOG_OPEN = 'SET_LOGIN_DIALOG_OPEN';
export const SET_LOGIN_DIALOG_BUSY = 'SET_LOGIN_DIALOG_BUSY';

export const SET_LOGIN_DIALOG_FIELD_VALUE = 'SET_LOGIN_DIALOG_FIELD_VALUE';

export const SET_LOGIN_DIALOG_FIELD_ERROR = 'SET_LOGIN_DIALOG_FIELD_ERROR';
export const RESET_LOGIN_DIALOG_FIELD_ERROR = 'RESET_LOGIN_DIALOG_FIELD_ERROR';

export const SET_LOGIN_DIALOG_GENERAL_ERROR = 'SET_LOGIN_DIALOG_GENERAL_ERROR';
export const RESET_LOGIN_DIALOG_GENERAL_ERROR = 'RESET_LOGIN_DIALOG_GENERAL_ERROR';

export const RESET_LOGIN_DIALOG_STATE = 'RESET_LOGIN_DIALOG_STATE';

export const SET_AUTHORIZATION_STATE = 'SET_AUTHORIZATION_STATE';
export const RESET_AUTHORIZATION_STATE = 'RESET_AUTHORIZATION_STATE';
