export const FETCH_TASKS = 'FETCH_TASKS';
export const SET_TASKS = 'SET_TASKS';

export const CREATE_TASK = 'CREATE_TASK';
export const EDIT_TASK = 'EDIT_TASK';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SET_TASK_LIST_STATE = 'SET_TASK_LIST_STATE';

export const SET_AUTHORIZATION_STATE = 'SET_AUTHORIZATION_STATE';

export const SET_DIALOG_OPEN = 'SET_DIALOG_OPEN';
export const SET_DIALOG_BUSY = 'SET_DIALOG_BUSY';

export const SET_DIALOG_FIELD_VALUE = 'SET_DIALOG_FIELD_VALUE';

export const SET_DIALOG_FIELD_ERROR = 'SET_DIALOG_FIELD_ERROR';
export const RESET_DIALOG_FIELD_ERROR = 'RESET_DIALOG_FIELD_ERROR';

export const SET_DIALOG_GENERAL_ERROR = 'SET_DIALOG_GENERAL_ERROR';
export const RESET_DIALOG_GENERAL_ERROR = 'RESET_DIALOG_GENERAL_ERROR';

export const RESET_DIALOG_STATE = 'RESET_DIALOG_STATE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const READ_AUTHORIZATION_DATA = 'READ_AUTHORIZATION_DATA';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
